spring:
  security:
    jwt:
      key: QnUgYml6aW0gc2VjcmV0IGtleS1kaXIuZnNkZmRiaHBnO25qO2xnaEJ1IGJpemltIHNlY3JldCBrZXktZGlyLmZzZGZkYmhwZztuajtsZ2hCdSBiaXppbSBzZWNyZXQga2V5LWRpci5mc2RmZGJocGc7bmo7bGdoQnUgYml6aW0gc2VjcmV0IGtleS1kaXIuZnNkZmRiaHBnO25qO2xnaA==
      access-expire-time: 300000
      refresh-expire-time: 360000